const FETCHING_CATEGORIES = 'FETCHING_CATEGORIES';
const FETCHING_MEALS = 'FETCHING_MEALS';
const FETCHING_DISH = 'FETCHING_DISHES';
const SET_INGREDIENTS = 'SET_INGREDIENTS';

const FETCH_LOADING = 'FETCH_LOADING';
const FETCHING_ERROR = 'FETCHING_ERROR';

export {
  FETCHING_CATEGORIES,
  FETCHING_MEALS,
  FETCHING_DISH,
  FETCH_LOADING,
  FETCHING_ERROR,
  SET_INGREDIENTS,
};
